workflows:
  default-workflow:
    name: Default Workflow

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --release
      - flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa